### ISSUE TITLE
An extra approach action generated

### ISSUE THREAD

**Issue by shiqizhang6** [bu-air-lab/asp_navigation#1]
Expected output :

approach(d1_m11,0) approach(d1_corr_m_corr_watson,3) goto(coffee_counter,6) gothrough(d1_corr_m_corr_watson,5) gothrough(d1_m11,2) opendoor(d1_m11,1) opendoor(d1_corr_m_corr_watson,4)

Observed output : approach(d1_m11,0) approach(d1_corr_m_corr_watson,3) approach(d1_corr_m_corr_watson,6) goto(coffee_counter,7) gothrough(d1_corr_m_corr_watson,5) gothrough(d1_m11,2) opendoor(d1_m11,1) opendoor(d1_corr_m_corr_watson,4)

**Comment by kchanda2** [comment]
The fix has been added to the code to avoid such extra actions.
